### ISSUE TITLE
Cannot launch apps or create shortcuts

### ISSUE THREAD

**Issue by tfranken90** [Fisch03/SDH-QuickLaunch#8] opened 2023-06-24 01:12 UTC
I'm running the latest versions of Chimera, DeckyLoader, and Quicklaunch, but the plugin is no longer launching apps or creating new shortcuts.

**Comment by Fisch03** [comment] 2023-06-24 04:04
Thanks for reporting! Unfortunately i cannot reproduce this on my Deck. I'll probably have to spin up a Chimera VM to test around a bit for myself.

In the meantime i am guessing you did the usual troubleshooting stuff (restarting, reinstalling etc..)?
If so, where exactly does it not launch? Does nothing happen or is there an infinite loading screen after launching?

**Comment by tfranken90** [comment] 2023-06-24 05:25
After selecting an app, if I click create shortcut or launch it simply does nothing. I've completely re-installed Decky and deleted all the directories and it's still not working. The logs don't seem to indicate any issues, although I occasionally see 

>PluginLoader[2994]: [base_events][ERROR]: Unclosed client session
>PluginLoader[2994]: client_session: <aiohttp.client.ClientSession object at 0x7f430852f340>

**Comment by jurassicplayer** [comment] 2023-06-30 12:10
SteamOS (Preview): OS v3.4.8 Build 20230531.1
DeckyLoader: v2.10.3-pre1
QuickLaunch: v1.1.0-1

@Fisch03 Pretty recently Apps.AddShortcut was changed to require more arguments (?), so it's probably just that
![](https://i.imgur.com/SUSx495.png)
Looking at bash-shortcuts, looks like it's going to be AddShortcut(appName, appPath, startDir, cliArgs)
https://github.com/Tormak9970/bash-shortcuts/commit/cf7ee7831bbd076272ec593703c34ca19a961ddb

**Comment by Fisch03** [comment] 2023-06-30 15:03
Ohh thanks, that's some great info!

Weird that it still worked on my deck last time i checked but oh well, i'll fix it asap!

**Comment by Fisch03** [comment] 2023-07-03 03:45
I'll close this for now since the update is out on the Testing Store. Do let me know if that fixes it for you :)

**Closed as completed** 2023-07-03 03:45 UTC

**Comment by tfranken90** [comment] 2023-07-03 03:52
@Fisch03 Looks like the testing version is working again. Thanks a lot! This plugin is essential for using the Steam OS interface.
